-- Английская локализация (enUS)
local L = LibStub("AceLocale-3.0"):NewLocale("Scrap_Sync", "enUS", true)

if L then
  L["Ready"] = "Scrap Sync loaded."
  L["NoCharSelected"] = "No character selected."
  L["NoScrapData"] = "No data for the selected character."
  L["CopyReportHeader"] = "Copying Scrap list from %s - %s"
  L["CopyReportFound"] = "Found"
  L["CopyReportAdded"] = "Added"
  L["CopyReportSkipped"] = "Skipped"
  L["ResetDone"] = "List reset."
  L["ConfirmCopy"] = "Copy Scrap list from selected character?"
  L["ResetConfirm"] = "Reset Scrap list for current character?"
  L["CopyScrap"] = "Copy"
  L["CopyScrapDesc"] = "Copy Scrap list from the selected character."
  L["Reset"] = "Reset"
  L["ResetDesc"] = "Reset Scrap list for the current character."
  L["Refresh"] = "Refresh"
  L["RefreshDesc"] = "Update data for the current character."
  L["ListRefreshed"] = "List updated."
  L["Character"] = "Character"
  L["SelectCharacterDesc"] = "Select a character to copy Scrap data from."
  L["TotalItems"] = "Total items"
  L["Rarity"] = "Rarity"
  L["Minimap"] = "Minimap icon"
  L["ShowIcon"] = "Show icon on the minimap."
  L["LMBTooltip"] = "Left-click: open settings"
  L["RMBTooltip"] = "Right-click: reset current list"
  L["DeleteDesc"] = "Delete the data for the current character."
  L["Junk"] = "junk"
  L["NotJunk"] = "keep"
  L["DeleteCharacter"] = "Delete character"
  L["DeleteCharacterConfirm"] = "Delete selected character data?"
  L["CannotDeleteCurrent"] = "You cannot delete the current character."
  L["LastSeen"] = "Last login"
  L["LastSeenNever"] = "never"
  L["Delete"] = "Delete"

  -- новые ключи
  L["ActivityChecking"] = "Check activity"
  L["ActivityCheckingDesc"] = "Enable or disable time-based activity checks"
  L["ActivityDays"] = "Number of days"
  L["ActivityDaysDesc"] = "Number of days of activity to check"

  -- строки, добавленные по вашему запросу
  L["ActivitySettings"] = "Настройки активности"
  L["ConfirmDeleteCharacter"] = "Вы уверены, что хотите удалить этого персонажа?"
  L["Yes"] = "Да"
  L["No"] = "Нет"
  L["CharacterDeleted"] = "Персонаж удален."
  L["ScrapToggleIntercepted"] = "Scrap.Toggle перехвачен и защищен"
  L["Days"] = "Кол-во дней"
  L["ActivityDaysForCheck"] = "Количество дней активности для проверки"
  L["CheckActivity"] = "Проверять активность"
  L["CheckActivityDesc"] = "Включить или выключить проверку активности по времени"
  L["Activity"] = "Настройки активности"
end

-- Русская локализация (ruRU)
local L = LibStub("AceLocale-3.0"):NewLocale("Scrap_Sync", "ruRU")

if L then
  L["Ready"] = "Scrap Sync загружен."
  L["NoCharSelected"] = "Не выбран персонаж."
  L["NoScrapData"] = "Нет данных у выбранного персонажа."
  L["CopyReportHeader"] = "Копирование списка Scrap с %s - %s"
  L["CopyReportFound"] = "Найдено"
  L["CopyReportAdded"] = "Добавлено"
  L["CopyReportSkipped"] = "Пропущено"
  L["ResetDone"] = "Список очищен."
  L["ConfirmCopy"] = "Скопировать список Scrap с выбранного персонажа?"
  L["ResetConfirm"] = "Очистить список Scrap у текущего персонажа?"
  L["CopyScrap"] = "Копировать"
  L["CopyScrapDesc"] = "Скопировать список Scrap с выбранного персонажа."
  L["Reset"] = "Сбросить"
  L["ResetDesc"] = "Сбросить список Scrap у текущего персонажа."
  L["Refresh"] = "Обновить"
  L["RefreshDesc"] = "Обновить данные для текущего персонажа."
  L["ListRefreshed"] = "Список обновлён."
  L["Character"] = "Персонаж"
  L["SelectCharacterDesc"] = "Выберите персонажа для копирования данных Scrap."
  L["TotalItems"] = "Всего предметов"
  L["Rarity"] = "Качество"
  L["Minimap"] = "Иконка на карте"
  L["ShowIcon"] = "Показывать иконку на миникарте."
  L["LMBTooltip"] = "ЛКМ: открыть настройки"
  L["RMBTooltip"] = "ПКМ: сбросить список"
  L["DeleteDesc"] = "Удалить данные текущего персонажа."
  L["Junk"] = "хлам"
  L["NotJunk"] = "не хлам"
  L["DeleteCharacter"] = "Удалить персонажа"
  L["DeleteCharacterConfirm"] = "Удалить данные выбранного персонажа?"
  L["CannotDeleteCurrent"] = "Нельзя удалить текущего персонажа."
  L["LastSeen"] = "Последний вход"
  L["LastSeenNever"] = "никогда"
  L["Delete"] = "Удалить"

  -- новые ключи
  L["ActivityChecking"] = "Проверять активность"
  L["ActivityCheckingDesc"] = "Включить или выключить проверку активности по времени"
  L["ActivityDays"] = "Кол-во дней"
  L["ActivityDaysDesc"] = "Количество дней активности для проверки"

  -- строки, добавленные по вашему запросу
  L["ActivitySettings"] = "Настройки активности"
  L["ConfirmDeleteCharacter"] = "Вы уверены, что хотите удалить этого персонажа?"
  L["Yes"] = "Да"
  L["No"] = "Нет"
  L["CharacterDeleted"] = "Персонаж удален."
  L["ScrapToggleIntercepted"] = "Scrap.Toggle перехвачен и защищен"
  L["Days"] = "Кол-во дней"
  L["ActivityDaysForCheck"] = "Количество дней активности для проверки"
  L["CheckActivity"] = "Проверять активность"
  L["CheckActivityDesc"] = "Включить или выключить проверку активности по времени"
  L["Activity"] = "Настройки активности"
end