local AceLocale = LibStub("AceLocale-3.0")
local L = AceLocale:NewLocale("Scrap_Sync", "enUS", true)

-- ============================================================================
-- ENGLISH (Base)
-- ============================================================================
if L then
  L["Ready"]             = "Scrap Sync loaded."
  L["NoCharSelected"]    = "No character selected."
  L["NoScrapData"]       = "No data for the selected character."
  L["CopyReportHeader"]  = "Copying Scrap list from %s - %s"
  L["CopyReportFound"]   = "Found"
  L["CopyReportAdded"]   = "Added"
  L["CopyReportSkipped"] = "Skipped"
  L["ResetDone"]         = "List reset."
  L["ConfirmCopy"]       = "Copy Scrap list from selected character?"
  L["ResetConfirm"]      = "Reset Scrap list for current character?"
  L["CopyScrap"]         = "Copy"
  L["CopyScrapDesc"]     = "Copy Scrap list from the selected character."
  L["Reset"]             = "Reset"
  L["ResetDesc"]         = "Reset Scrap list for the current character."
  L["Refresh"]           = "Refresh"
  L["RefreshDesc"]       = "Update data for the current character."
  L["ListRefreshed"]     = "List updated."
  L["Character"]         = "Character"
  L["SelectCharacterDesc"]= "Select a character to copy Scrap data from."
  L["TotalItems"]        = "Total items"
  L["Rarity"]            = "Rarity"
  L["Minimap"]           = "Minimap icon"
  L["ShowIcon"]          = "Show icon on the minimap."
  L["LMBTooltip"]        = "Left-click: open settings"
  L["RMBTooltip"]        = "Right-click: reset current list"
  L["Junk"]              = "junk"
  L["NotJunk"]           = "keep"
  L["DebugMode"]         = "Debug mode"
  L["DebugModeDesc"]     = "Enable detailed debug messages."
  L["DebugEnabled"]      = "Debug enabled."
  L["DebugDisabled"]     = "Debug disabled."
  L["AltClickTest"]      = "Alt+Click (test)"
  L["AltClickTestDesc"]  = "Temporarily enable Alt+Click to add items. Only when debug is active."
  L["AltClickEnabled"]   = "Alt+Click enabled."
  L["AltClickDisabled"]  = "Alt+Click disabled."
  L["BindingNoItem"]     = "Could not identify item. Hover over an item icon in your bags or merchant window."
  L["AddedToJunk"]       = "Added to junk list: %s"
  L["RemovedFromJunk"]   = "Removed from junk list: %s"
end

-- ============================================================================
-- RUSSIAN (ruRU)
-- ============================================================================
L = AceLocale:NewLocale("Scrap_Sync", "ruRU")
if L then
  L["Ready"]             = "Scrap Sync загружен."
  L["NoCharSelected"]    = "Не выбран персонаж."
  L["NoScrapData"]       = "Нет данных у выбранного персонажа."
  L["CopyReportHeader"]  = "Копирование списка Scrap с %s - %s"
  L["CopyReportFound"]   = "Найдено"
  L["CopyReportAdded"]   = "Добавлено"
  L["CopyReportSkipped"] = "Пропущено"
  L["ResetDone"]         = "Список очищен."
  L["ConfirmCopy"]       = "Скопировать список Scrap с выбранного персонажа?"
  L["ResetConfirm"]      = "Очистить список Scrap у текущего персонажа?"
  L["CopyScrap"]         = "Копировать"
  L["CopyScrapDesc"]     = "Скопировать список Scrap с выбранного персонажа."
  L["Reset"]             = "Сбросить"
  L["ResetDesc"]         = "Сбросить список Scrap у текущего персонажа."
  L["Refresh"]           = "Обновить"
  L["RefreshDesc"]       = "Обновить данные для текущего персонажа."
  L["ListRefreshed"]     = "Список обновлён."
  L["Character"]         = "Персонаж"
  L["SelectCharacterDesc"]= "Выберите персонажа для копирования данных Scrap."
  L["TotalItems"]        = "Всего предметов"
  L["Rarity"]            = "Качество"
  L["Minimap"]           = "Иконка на карте"
  L["ShowIcon"]          = "Показывать иконку на миникарте."
  L["LMBTooltip"]        = "ЛКМ: открыть настройки"
  L["RMBTooltip"]        = "ПКМ: сбросить список"
  L["Junk"]              = "хлам"
  L["NotJunk"]           = "не хлам"
  L["DebugMode"]         = "Режим отладки"
  L["DebugModeDesc"]     = "Включить подробные сообщения отладки."
  L["DebugEnabled"]      = "Отладка включена."
  L["DebugDisabled"]     = "Отладка выключена."
  L["AltClickTest"]      = "Alt+Click (тест)"
  L["AltClickTestDesc"]  = "Временно включить добавление предметов по Alt+Click. Только при включённой отладке."
  L["AltClickEnabled"]   = "Alt+Click активирован."
  L["AltClickDisabled"]  = "Alt+Click отключен."
  L["BindingNoItem"]     = "Не удалось определить предмет. Наведите курсор на иконку предмета в сумке или в окне торговца."
  L["AddedToJunk"]       = "Добавлено в список хлама: %s"
  L["RemovedFromJunk"]   = "Удалено из списка хлама: %s"
end

-- ============================================================================
-- GERMAN (deDE)
-- ============================================================================
L = AceLocale:NewLocale("Scrap_Sync", "deDE")
if L then
  L["Ready"]             = "Scrap Sync geladen."
  L["NoCharSelected"]    = "Kein Charakter ausgewählt."
  L["NoScrapData"]       = "Keine Daten für den ausgewählten Charakter."
  L["CopyReportHeader"]  = "Kopiere Scrap-Liste von %s - %s"
  L["CopyReportFound"]   = "Gefunden"
  L["CopyReportAdded"]   = "Hinzugefügt"
  L["CopyReportSkipped"] = "Übersprungen"
  L["ResetDone"]         = "Liste zurückgesetzt."
  L["ConfirmCopy"]       = "Scrap-Liste vom ausgewählten Charakter kopieren?"
  L["ResetConfirm"]      = "Scrap-Liste für aktuellen Charakter zurücksetzen?"
  L["CopyScrap"]         = "Kopieren"
  L["CopyScrapDesc"]     = "Scrap-Liste vom ausgewählten Charakter kopieren."
  L["Reset"]             = "Zurücksetzen"
  L["ResetDesc"]         = "Scrap-Liste für den aktuellen Charakter zurücksetzen."
  L["Refresh"]           = "Aktualisieren"
  L["RefreshDesc"]       = "Daten für den aktuellen Charakter aktualisieren."
  L["ListRefreshed"]     = "Liste aktualisiert."
  L["Character"]         = "Charakter"
  L["SelectCharacterDesc"]= "Wähle einen Charakter zum Kopieren der Scrap-Daten."
  L["TotalItems"]        = "Gesamtanzahl"
  L["Rarity"]            = "Qualität"
  L["Minimap"]           = "Minikartensymbol"
  L["ShowIcon"]          = "Symbol auf der Minikarte anzeigen."
  L["LMBTooltip"]        = "Linksklick: Einstellungen öffnen"
  L["RMBTooltip"]        = "Rechtsklick: aktuelle Liste zurücksetzen"
  L["Junk"]              = "Müll"
  L["NotJunk"]           = "behalten"
  L["DebugMode"]         = "Debug-Modus"
  L["DebugModeDesc"]     = "Detaillierte Debug-Meldungen aktivieren."
  L["DebugEnabled"]      = "Debug aktiviert."
  L["DebugDisabled"]     = "Debug deaktiviert."
  L["AltClickTest"]      = "Alt+Click (Test)"
  L["AltClickTestDesc"]  = "Vorübergehend Alt+Click zum Hinzufügen von Gegenständen aktivieren. Nur bei aktivem Debug."
  L["AltClickEnabled"]   = "Alt+Click aktiviert."
  L["AltClickDisabled"]  = "Alt+Click deaktiviert."
  L["BindingNoItem"]     = "Gegenstand nicht erkannt. Zeiger über ein Gegenstandssymbol im Inventar oder Händlerfenster bewegen."
  L["AddedToJunk"]       = "Zur Junkliste hinzugefügt: %s"
  L["RemovedFromJunk"]   = "Von der Junkliste entfernt: %s"
end

-- ============================================================================
-- FRENCH (frFR)
-- ============================================================================
L = AceLocale:NewLocale("Scrap_Sync", "frFR")
if L then
  L["Ready"]             = "Scrap Sync chargé."
  L["NoCharSelected"]    = "Aucun personnage sélectionné."
  L["NoScrapData"]       = "Aucune donnée pour le personnage sélectionné."
  L["CopyReportHeader"]  = "Copie de la liste Scrap depuis %s - %s"
  L["CopyReportFound"]   = "Trouvé"
  L["CopyReportAdded"]   = "Ajouté"
  L["CopyReportSkipped"] = "Ignoré"
  L["ResetDone"]         = "Liste réinitialisée."
  L["ConfirmCopy"]       = "Copier la liste Scrap du personnage sélectionné ?"
  L["ResetConfirm"]      = "Réinitialiser la liste Scrap du personnage actuel ?"
  L["CopyScrap"]         = "Copier"
  L["CopyScrapDesc"]     = "Copier la liste Scrap depuis le personnage sélectionné."
  L["Reset"]             = "Réinitialiser"
  L["ResetDesc"]         = "Réinitialiser la liste Scrap du personnage actuel."
  L["Refresh"]           = "Actualiser"
  L["RefreshDesc"]       = "Mettre à jour les données du personnage actuel."
  L["ListRefreshed"]     = "Liste mise à jour."
  L["Character"]         = "Personnage"
  L["SelectCharacterDesc"]= "Sélectionnez un personnage pour copier les données Scrap."
  L["TotalItems"]        = "Total objets"
  L["Rarity"]            = "Qualité"
  L["Minimap"]           = "Icône minicarte"
  L["ShowIcon"]          = "Afficher l'icône sur la minicarte."
  L["LMBTooltip"]        = "Clic gauche : ouvrir les paramètres"
  L["RMBTooltip"]        = "Clic droit : réinitialiser la liste"
  L["Junk"]              = "rebut"
  L["NotJunk"]           = "garder"
  L["DebugMode"]         = "Mode débogage"
  L["DebugModeDesc"]     = "Activer les messages de débogage détaillés."
  L["DebugEnabled"]      = "Débogage activé."
  L["DebugDisabled"]     = "Débogage désactivé."
  L["AltClickTest"]      = "Alt+Clic (test)"
  L["AltClickTestDesc"]  = "Activer temporairement Alt+Clic pour ajouter des objets. Uniquement lorsque le débogage est actif."
  L["AltClickEnabled"]   = "Alt+Clic activé."
  L["AltClickDisabled"]  = "Alt+Clic désactivé."
  L["BindingNoItem"]     = "Impossible d'identifier l'objet. Survolez l'icône d'un objet dans votre sac ou la fenêtre du marchand."
  L["AddedToJunk"]       = "Ajouté à la liste de rebut: %s"
  L["RemovedFromJunk"]   = "Retiré de la liste de rebut: %s"
end

-- ============================================================================
-- SPANISH (esES / esMX)
-- ============================================================================
L = AceLocale:NewLocale("Scrap_Sync", "esES") or AceLocale:NewLocale("Scrap_Sync", "esMX")
if L then
  L["Ready"]             = "Scrap Sync cargado."
  L["NoCharSelected"]    = "Ningún personaje seleccionado."
  L["NoScrapData"]       = "No hay datos para el personaje seleccionado."
  L["CopyReportHeader"]  = "Copiando lista de Scrap desde %s - %s"
  L["CopyReportFound"]   = "Encontrado"
  L["CopyReportAdded"]   = "Añadido"
  L["CopyReportSkipped"] = "Omitido"
  L["ResetDone"]         = "Lista reiniciada."
  L["ConfirmCopy"]       = "¿Copiar lista de Scrap del personaje seleccionado?"
  L["ResetConfirm"]      = "¿Reiniciar lista de Scrap del personaje actual?"
  L["CopyScrap"]         = "Copiar"
  L["CopyScrapDesc"]     = "Copiar lista de Scrap del personaje seleccionado."
  L["Reset"]             = "Reiniciar"
  L["ResetDesc"]         = "Reiniciar lista de Scrap del personaje actual."
  L["Refresh"]           = "Actualizar"
  L["RefreshDesc"]       = "Actualizar datos del personaje actual."
  L["ListRefreshed"]     = "Lista actualizada."
  L["Character"]         = "Personaje"
  L["SelectCharacterDesc"]= "Selecciona un personaje para copiar los datos de Scrap."
  L["TotalItems"]        = "Total objetos"
  L["Rarity"]            = "Calidad"
  L["Minimap"]           = "Icono en minimapa"
  L["ShowIcon"]          = "Mostrar icono en el minimapa."
  L["LMBTooltip"]        = "Clic izquierdo: abrir opciones"
  L["RMBTooltip"]        = "Clic derecho: reiniciar lista"
  L["Junk"]              = "basura"
  L["NotJunk"]           = "conservar"
  L["DebugMode"]         = "Modo depuración"
  L["DebugModeDesc"]     = "Activar mensajes detallados de depuración."
  L["DebugEnabled"]      = "Depuración activada."
  L["DebugDisabled"]     = "Depuración desactivada."
  L["AltClickTest"]      = "Alt+Clic (prueba)"
  L["AltClickTestDesc"]  = "Activar temporalmente Alt+Clic para añadir objetos. Solo cuando la depuración está activa."
  L["AltClickEnabled"]   = "Alt+Clic activado."
  L["AltClickDisabled"]  = "Alt+Clic desactivado."
  L["BindingNoItem"]     = "No se pudo identificar el objeto. Coloca el cursor sobre el icono de un objeto en tus bolsas o en la ventana del vendedor."
  L["AddedToJunk"]       = "Añadido a la lista de basura: %s"
  L["RemovedFromJunk"]   = "Eliminado de la lista de basura: %s"
end

-- ============================================================================
-- KOREAN (koKR)
-- ============================================================================
L = AceLocale:NewLocale("Scrap_Sync", "koKR")
if L then
  L["Ready"]             = "Scrap Sync 로드됨."
  L["NoCharSelected"]    = "선택된 캐릭터가 없습니다."
  L["NoScrapData"]       = "선택한 캐릭터에 데이터가 없습니다."
  L["CopyReportHeader"]  = "%s - %s에서 Scrap 목록 복사"
  L["CopyReportFound"]   = "발견"
  L["CopyReportAdded"]   = "추가됨"
  L["CopyReportSkipped"] = "건너뜀"
  L["ResetDone"]         = "목록 초기화됨."
  L["ConfirmCopy"]       = "선택한 캐릭터의 Scrap 목록을 복사하시겠습니까?"
  L["ResetConfirm"]      = "현재 캐릭터의 Scrap 목록을 초기화하시겠습니까?"
  L["CopyScrap"]         = "복사"
  L["CopyScrapDesc"]     = "선택한 캐릭터의 Scrap 목록을 복사합니다."
  L["Reset"]             = "초기화"
  L["ResetDesc"]         = "현재 캐릭터의 Scrap 목록을 초기화합니다."
  L["Refresh"]           = "새로고침"
  L["RefreshDesc"]       = "현재 캐릭터의 데이터를 업데이트합니다."
  L["ListRefreshed"]     = "목록 업데이트됨."
  L["Character"]         = "캐릭터"
  L["SelectCharacterDesc"]= "Scrap 데이터를 복사할 캐릭터를 선택하세요."
  L["TotalItems"]        = "전체 아이템"
  L["Rarity"]            = "희귀도"
  L["Minimap"]           = "미니맵 아이콘"
  L["ShowIcon"]          = "미니맵에 아이콘 표시."
  L["LMBTooltip"]        = "왼쪽 클릭: 설정 열기"
  L["RMBTooltip"]        = "오른쪽 클릭: 현재 목록 초기화"
  L["Junk"]              = "잡동사니"
  L["NotJunk"]           = "유지"
  L["DebugMode"]         = "디버그 모드"
  L["DebugModeDesc"]     = "자세한 디버그 메시지를 활성화합니다."
  L["DebugEnabled"]      = "디버그 활성화됨."
  L["DebugDisabled"]     = "디버그 비활성화됨."
  L["AltClickTest"]      = "Alt+클릭 (테스트)"
  L["AltClickTestDesc"]  = "Alt+클릭으로 아이템 추가를 임시로 활성화합니다. 디버그 모드일 때만 표시됩니다."
  L["AltClickEnabled"]   = "Alt+클릭 활성화됨."
  L["AltClickDisabled"]  = "Alt+클릭 비활성화됨."
  L["BindingNoItem"]     = "아이템을 식별할 수 없습니다. 가방이나 상인 창의 아이템 아이콘 위에 커서를 올려놓으세요."
  L["AddedToJunk"]       = "잡동사니 목록에 추가됨: %s"
  L["RemovedFromJunk"]   = "잡동사니 목록에서 제거됨: %s"
end

-- ============================================================================
-- SIMPLIFIED CHINESE (zhCN)
-- ============================================================================
L = AceLocale:NewLocale("Scrap_Sync", "zhCN")
if L then
  L["Ready"]             = "Scrap Sync 已加载。"
  L["NoCharSelected"]    = "未选择角色。"
  L["NoScrapData"]       = "所选角色没有数据。"
  L["CopyReportHeader"]  = "从 %s - %s 复制 Scrap 列表"
  L["CopyReportFound"]   = "找到"
  L["CopyReportAdded"]   = "已添加"
  L["CopyReportSkipped"] = "已跳过"
  L["ResetDone"]         = "列表已重置。"
  L["ConfirmCopy"]       = "从所选角色复制 Scrap 列表？"
  L["ResetConfirm"]      = "重置当前角色的 Scrap 列表？"
  L["CopyScrap"]         = "复制"
  L["CopyScrapDesc"]     = "从所选角色复制 Scrap 列表。"
  L["Reset"]             = "重置"
  L["ResetDesc"]         = "重置当前角色的 Scrap 列表。"
  L["Refresh"]           = "刷新"
  L["RefreshDesc"]       = "更新当前角色的数据。"
  L["ListRefreshed"]     = "列表已更新。"
  L["Character"]         = "角色"
  L["SelectCharacterDesc"]= "选择一个角色以复制 Scrap 数据。"
  L["TotalItems"]        = "总计物品"
  L["Rarity"]            = "品质"
  L["Minimap"]           = "小地图图标"
  L["ShowIcon"]          = "在小地图上显示图标。"
  L["LMBTooltip"]        = "左键：打开设置"
  L["RMBTooltip"]        = "右键：重置当前列表"
  L["Junk"]              = "垃圾"
  L["NotJunk"]           = "保留"
  L["DebugMode"]         = "调试模式"
  L["DebugModeDesc"]     = "启用详细的调试信息。"
  L["DebugEnabled"]      = "调试已启用。"
  L["DebugDisabled"]     = "调试已禁用。"
  L["AltClickTest"]      = "Alt+点击 (测试)"
  L["AltClickTestDesc"]  = "临时启用 Alt+点击 添加物品。仅在调试模式激活时显示。"
  L["AltClickEnabled"]   = "Alt+点击 已启用。"
  L["AltClickDisabled"]  = "Alt+点击 已禁用。"
  L["BindingNoItem"]     = "无法识别物品。请将鼠标悬停在背包或商人窗口中的物品图标上。"
  L["AddedToJunk"]       = "已添加到垃圾列表：%s"
  L["RemovedFromJunk"]   = "已从垃圾列表移除：%s"
end

-- ============================================================================
-- TRADITIONAL CHINESE (zhTW)
-- ============================================================================
L = AceLocale:NewLocale("Scrap_Sync", "zhTW")
if L then
  L["Ready"]             = "Scrap Sync 已加載。"
  L["NoCharSelected"]    = "未選擇角色。"
  L["NoScrapData"]       = "所選角色沒有數據。"
  L["CopyReportHeader"]  = "從 %s - %s 複製 Scrap 清單"
  L["CopyReportFound"]   = "找到"
  L["CopyReportAdded"]   = "已添加"
  L["CopyReportSkipped"] = "已跳過"
  L["ResetDone"]         = "清單已重置。"
  L["ConfirmCopy"]       = "從所選角色複製 Scrap 清單？"
  L["ResetConfirm"]      = "重置當前角色的 Scrap 清單？"
  L["CopyScrap"]         = "複製"
  L["CopyScrapDesc"]     = "從所選角色複製 Scrap 清單。"
  L["Reset"]             = "重置"
  L["ResetDesc"]         = "重置當前角色的 Scrap 清單。"
  L["Refresh"]           = "刷新"
  L["RefreshDesc"]       = "更新當前角色的數據。"
  L["ListRefreshed"]     = "清單已更新。"
  L["Character"]         = "角色"
  L["SelectCharacterDesc"]= "選擇一個角色以複製 Scrap 數據。"
  L["TotalItems"]        = "總計物品"
  L["Rarity"]            = "品質"
  L["Minimap"]           = "小地圖圖示"
  L["ShowIcon"]          = "在小地圖上顯示圖示。"
  L["LMBTooltip"]        = "左鍵：開啟設定"
  L["RMBTooltip"]        = "右鍵：重置當前清單"
  L["Junk"]              = "垃圾"
  L["NotJunk"]           = "保留"
  L["DebugMode"]         = "除錯模式"
  L["DebugModeDesc"]     = "啟用詳細的除錯訊息。"
  L["DebugEnabled"]      = "除錯已啟用。"
  L["DebugDisabled"]     = "除錯已停用。"
  L["AltClickTest"]      = "Alt+點擊 (測試)"
  L["AltClickTestDesc"]  = "暫時啟用 Alt+點擊 添加物品。僅在除錯模式啟用時顯示。"
  L["AltClickEnabled"]   = "Alt+點擊 已啟用。"
  L["AltClickDisabled"]  = "Alt+點擊 已停用。"
  L["BindingNoItem"]     = "無法識別物品。請將滑鼠懸停在背包或商人視窗中的物品圖示上。"
  L["AddedToJunk"]       = "已添加到垃圾清單：%s"
  L["RemovedFromJunk"]   = "已從垃圾清單移除：%s"
end

-- ============================================================================
-- INTEGRATION INTO SCRAP ORIGINALS (Merchant, Options, Visualizer)
-- ============================================================================
if Scrap_Locals then
    local SL = Scrap_Locals
    local lang = GetLocale()

    if lang == 'ruRU' then
        SL["AutoSell"] = "Авто продажа"
        SL["AutoSellDesc"] = "Если включено, Scrap автоматически будет продавать хлам когда вы посещаете торговца."
        SL["ShowTutorials"] = "Показать учебник"
        SL["Tutorial"] = "Вы сейчас используете Scrap - дополнение, которое позволяет вам продавать весь ваш имеющийся хлам нажатием одной кнопки!|n|n|cffffd200Левая кнопка мыши|r на кнопке Scrap продаст ваш хлам. |cffffd200Правая кнопка мыши|r откроет вам дополнительные опции."
        SL["Tutorial2"] = "Вы можете указать, какие предметы вы хотите, чтобы Scrap продавал или нет: для добавления или удаления предмета с вашего |cffffd200Списка хлама|r, перетащите предмет на кнопку Scrap."
        SL["Visualizer"] = "Визуализатор"; SL["Merchant"] = "Торговец"; SL["List"] = "Список хлама"
    elseif lang == 'zhCN' then
        SL["AutoSell"] = "自动出售"
        SL["AutoSellDesc"] = "开启此功能，Scrap会在你访问商人时自动出售所有垃圾。"
        SL["ShowTutorials"] = "显示教学"
        SL["Tutorial"] = "你正在使用Scrap，本插件可以让你在商人处一键出售所有你不需要的物品。|n|n|cffffd200左键单击|rScrap按钮出售所有垃圾。|cffffd200右键单击|rScrap按钮弹出选项。"
        SL["Tutorial2"] = "你可以自行决定Scrap帮你出售哪些物品: 如要对|cffffd200垃圾列表|r进行添加或删除，只需将物品从你的背包拖拽到Scrap按钮。"
        SL["Visualizer"] = "可视化器"; SL["Merchant"] = "商人"; SL["List"] = "垃圾列表"
    elseif lang == 'zhTW' then
        SL["AutoSell"] = "自動出售"
        SL["AutoSellDesc"] = "開啟次功能，Scrap會在你訪問商人時自動出售所有垃圾。"
        SL["ShowTutorials"] = "顯示教學"
        SL["Tutorial"] = "你正在使用Scrap，本組件可讓你在商人處單擊出售所有你不需要的物品。|n|n|cffffd200左鍵點擊|rScrap按鈕出售所有垃圾。|cffffd200右鍵點擊|rScrap按鈕顯示選單。"
        SL["Tutorial2"] = "你可以自行決定Scrap幫助你出售哪些物品: 如要對|cffffd200垃圾清單|r進行添加或移除，只需將物品從你的背包拖拽到Scrap按鈕。"
        SL["Visualizer"] = "可視化器"; SL["Merchant"] = "商人"; SL["List"] = "垃圾清單"
    elseif lang == 'deDE' then
        SL["AutoSell"] = "Automatisch verkaufen"
        SL["AutoSellDesc"] = "Wenn aktiviert, wird Scrap deinen Müll automatisch beim Händler verkaufen."
        SL["ShowTutorials"] = "Zeige Anleitungen"
        SL["Tutorial"] = "Du benutzt nun Scrap, ein Addon zum Verkaufen all der Gegenstände...|n|n|cffffd200Linksklick|r..."
        SL["Tutorial2"] = "Du kannst einstellen, welche Gegenstände..."
        SL["Visualizer"] = "Visualisierung"; SL["Merchant"] = "Händler"; SL["List"] = "Junkliste"
    elseif lang == 'esES' or lang == 'esMX' then
        SL["AutoSell"] = "Auto Vender"
        SL["AutoSellDesc"] = "Si está habilitado, Scrap venderá automáticamente toda tu basura..."
        SL["ShowTutorials"] = "Mostrar Tutoriales"
        SL["Tutorial"] = "Estás usando Scrap, un addon..."
        SL["Visualizer"] = "Visualizador"; SL["Merchant"] = "Vendedor"; SL["List"] = "Lista de basura"
    elseif lang == 'frFR' then
        SL["AutoSell"] = "Vente automatique"
        SL["AutoSellDesc"] = "Si actif, Scrap vendra automatiquement tous vos objets gris..."
        SL["ShowTutorials"] = "Afficher les didacticiels"
        SL["Tutorial"] = "Vous utilisez maintenant Scrap, un add-on..."
        SL["Visualizer"] = "Visualiseur"; SL["Merchant"] = "Marchand"; SL["List"] = "Liste de rebut"
    end
end